### ISSUE TITLE
NullPointer in RolloverButtonListener

### ISSUE THREAD

**Issue by PirolA** [Insubstantial/insubstantial#81]
Hello shemnon, 

thanks for the efforts that you put into this project.
You had already help me on some points.

I had a little break (3 months maternity leave;)

I need your help again.
I often get the following message, which can not reproduce.
Sometimes when hovering the mouse over different components, sometimes when starting my application, ...

For help, I would be grateful

java.lang.NullPointerException
    at org.pushingpixels.substance.internal.utils.RolloverButtonListener.focusGained(RolloverButtonListener.java:173)
    at java.awt.AWTEventMulticaster.focusGained(Unknown Source)
    at java.awt.Component.processFocusEvent(Unknown Source)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
    at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
    at java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.SequencedEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by kschaefe** [comment]
According to the JavaDoc MouseInfo.getPointerInfo returns null on systems without a mouse.  Otherwise, I can't see how you could generate a NPE in that code.

**Comment by PirolA** [comment]
The error occurs on several different computers and a mouse is definitely connected.
I can not explain, however, there is definitely a bug here. This should perhaps be more defensive programming to prevent the Nullpointer.

**Comment by PirolA** [comment]
See the bug http://java.net/jira/browse/SUBSTANCE-504
